import re
import sys

filepath = r"d:\fintech\backend\migrations\versions\0005_reconcile_production_schema.py"
with open(filepath, "r") as f:
    lines = f.readlines()

new_lines = []
current_col = None

for line in lines:
    # capture op.alter_column('table', 'col',
    m = re.search(r"op\.alter_column\('[^']+',\s*'([^']+)'", line)
    if m:
        current_col = m.group(1)
        
    new_lines.append(line)
    
    # When we see type_=sa.Uuid(), we insert postgresql_using
    if "type_=sa.Uuid()" in line and current_col:
        new_lines.append(f"               postgresql_using='{current_col}::uuid',\n")

content = "".join(new_lines)

# Inject the skip logic at the start of upgrade()
skip_logic = """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if inspector.has_table('policies'):
        columns = [c['name'] for c in inspector.get_columns('policies')]
        if 'start_at' in columns:
            print("Skipping reconciliation on production database because start_at already exists.")
            return
"""

content = content.replace(
    "def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###",
    "def upgrade() -> None:\n    # ### commands auto generated by Alembic - please adjust! ###" + skip_logic
)

with open(filepath, "w") as f:
    f.write(content)

print("Patched 0005 successfully.")
