"""phase6_voice_call_job

Revision ID: 40d6ad434813
Revises: 5525a7a05172
Create Date: 2026-09-29 04:30:05.302845+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40d6ad434813'
down_revision: Union[str, None] = '5525a7a05172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_call_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('handoff_id', sa.Uuid(), nullable=False),
    sa.Column('policyholder_id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('provider_call_id', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('call_script_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['handoff_id'], ['ai_assistance_handoffs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policyholder_id'], ['policyholders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handoff_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_call_jobs')
    # ### end Alembic commands ###

